FROM node:20-alpine

RUN npm config set fetch-retry-maxtimeout 600000 \
    && npm config set fetch-retry-mintimeout 10000 \
    && npm config set fetch-retries 5

WORKDIR /app

COPY package*.json ./

RUN npm install --network-timeout=100000 --registry=https://registry.npmjs.org/

COPY . .

ENV PORT=3000
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

EXPOSE ${PORT}

CMD ["npm", "run", "dev"]