services:
  # Backend Service
  - type: web
    name: storylabs-api
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: ACCESS_CODE
        sync: false
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - backend/**

  # Frontend Service
  - type: web
    name: storylabs
    env: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://storylabs-api.onrender.com
      - key: NEXT_PUBLIC_ACCESS_CODE
        sync: false
    buildFilter:
      paths:
        - frontend/**